// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NingsMart.Models;

namespace NingsMart.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20191024132134_InitailCreate1")]
    partial class InitailCreate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NingsMart.Models.ProductViewModel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Price")
                        .HasColumnName("nvarchar(max)")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnName("nvarchar(250)")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qauntity")
                        .HasColumnName("nvarchar(100)")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("productTble");
                });
#pragma warning restore 612, 618
        }
    }
}
